INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Ocean Cleanup", "Environment", 10000, "5/12/19", "5/17/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Food Drive", "Homeless", 500, "3/16/20", "3/26/20");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Children's Book Drive", "Children", 125, "5/12/19", "5/17/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Shelter Fundraiser", "Homeless", 5000, "5/12/19", "5/12/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Alzheimers Run", "Seniors", 100, "6/1/17", "6/30/17");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Sex Ed", "Teens", 65, "6/27/19", "7/4/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Swim Lessons", "Children", 100, "5/12/19", "7/31/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Dog Harnesses", "Disabled", 500, "7/1/19", "7/5/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("Instruments", "Disabled", 315, "5/1/19", "5/31/19");
INSERT INTO projects (title, category, funding_goal, start_date, end_date) VALUES ("PTSD Counseling", "Military", 80, "4/1/19", "4/31/19");

INSERT INTO users (name, age) VALUES ("Sydney Hunter", 22);
INSERT INTO users (name, age) VALUES ("Luc Flynn", 29);
INSERT INTO users (name, age) VALUES ("Raymond Hunter", 18);
INSERT INTO users (name, age) VALUES ("Nyah Guzman", 18);
INSERT INTO users (name, age) VALUES ("Lem Hunter", 55);
INSERT INTO users (name, age) VALUES ("Anaclaire Hunter", 54);
INSERT INTO users (name, age) VALUES ("Kory Cordova", 21);
INSERT INTO users (name, age) VALUES ("Makenna Hunter", 23);
INSERT INTO users (name, age) VALUES ("Lenny Smith", 38);
INSERT INTO users (name, age) VALUES ("David Bowie", 84);
INSERT INTO users (name, age) VALUES ("Tom DeLonge", 27);
INSERT INTO users (name, age) VALUES ("Hayley Williams", 27);
INSERT INTO users (name, age) VALUES ("Jason Banning", 27);
INSERT INTO users (name, age) VALUES ("Morgan Johnson", 26);
INSERT INTO users (name, age) VALUES ("Helen Carrey", 27);
INSERT INTO users (name, age) VALUES ("Taylor Anderson", 24);
INSERT INTO users (name, age) VALUES ("Kate Spade", 31);
INSERT INTO users (name, age) VALUES ("Sean Hannity", 32);
INSERT INTO users (name, age) VALUES ("Brady Jones", 19);
INSERT INTO users (name, age) VALUES ("Jared Singer", 22);

INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 1, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 1, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 1, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 2, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 8);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 3, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 4, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 5, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 5, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 7);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 6, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 7, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (100, 8, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 8, 2);
INSERT INTO pledges (amount, user_id, project_id) VALUES (35, 9, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 10, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (30, 11, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 12, 1);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 13, 10);
INSERT INTO pledges (amount, user_id, project_id) VALUES (10, 14, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (40, 15, 3);
INSERT INTO pledges (amount, user_id, project_id) VALUES (20, 16, 6);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 17, 9);
INSERT INTO pledges (amount, user_id, project_id) VALUES (50, 18, 5);
INSERT INTO pledges (amount, user_id, project_id) VALUES (15, 19, 4);
INSERT INTO pledges (amount, user_id, project_id) VALUES (25, 20, 1);